version: '3.8'

services:
  livekit:
    image: livekit/livekit-server
    ports:
      - "7880:7880"    # HTTP port
      - "7881:7881"    # TCP relay port
      - "50000-50100:50000-50100/udp" # UDP media ports
    configs:
      - source: livekit_config
        target: /livekit.yaml
    command: --config /livekit.yaml
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
configs:
  livekit_config:
    file: ./livekit.yaml